"""add threshold_config table

Revision ID: 208f95f208f7
Revises: a1b2c3d4e5f6
Create Date: 2026-09-29 15:57:21.921461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208f95f208f7'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threshold_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mfa_threshold', sa.Float(), nullable=False),
    sa.Column('block_threshold', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threshold_config')
    # ### end Alembic commands ###
