"""make ml_model_versions metrics nullable

Revision ID: 5b7d77744993
Revises: ac87cda64b3e
Create Date: 2026-09-30 08:27:12.401718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7d77744993'
down_revision: Union[str, Sequence[str], None] = 'ac87cda64b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ml_model_versions', 'training_data_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ml_model_versions', 'false_positive_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ml_model_versions', 'detection_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ml_model_versions', 'detection_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ml_model_versions', 'false_positive_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ml_model_versions', 'training_data_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
