"""add acknowledged_at to alerts

Revision ID: 731732bfb982
Revises: 208f95f208f7
Create Date: 2026-09-29 16:01:22.967403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '731732bfb982'
down_revision: Union[str, Sequence[str], None] = '208f95f208f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'acknowledged_at')
    # ### end Alembic commands ###
