"""add login_count to device_registry

Revision ID: ac87cda64b3e
Revises: 731732bfb982
Create Date: 2026-09-29 16:05:59.442022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac87cda64b3e'
down_revision: Union[str, Sequence[str], None] = '731732bfb982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_registry', sa.Column('login_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_registry', 'login_count')
    # ### end Alembic commands ###
